config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :users
  resources :messages
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  scope :for_display, -> { order(:created_at).last(50) }

  def mentions
    content.scan(/@(#{User::NAME_REGEX})/).flatten.map do |username|
      User.find_by(username: username)
    end.compact
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  NAME_REGEX = /\w+/
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       format: { with: /\A#{NAME_REGEX}\z/i },
                       length: { maximum: 15 }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :logged_in_user
  before_action :get_messages

  def index
  end

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast 'room_channel',
                                   message: render_message(message)

      message.mentions.each do |mention|
        ActionCable.server.broadcast "room_channel_user_#{mention.id}",
                                      mention: true,
                                      from: message.user.username.to_s
      end
    end
  end

  private

    def get_messages
      @messages = Message.for_display
      @message  = current_user.messages.build
    end

    def message_params
      params.require(:message).permit(:content)
    end

    def render_message(message)
      render( partial: 'message', locals: {message: message})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to messages_url
    else
      flash.now[:danger] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to messages_url
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

# Returns HTML from input text using GitHub-flavored Markdown.
  def markdown_to_html(text)
    Kramdown::Document.new(text, input: 'GFM').to_html
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    cookies.signed[:user_id] = user.id
  end

  def log_out
    cookies.delete(:user_id)
    @current_user = nil
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="header">
  <a href="/" class="header-logo"><%= render 'layouts/logo' %></a>
  <ul class="header-nav">
    <% if logged_in? %>
    <li><%= link_to "Sign out", logout_path, method: :delete %>
    <% end %>
  </ul>
</header>

app/views/layouts/_logo.html.erb
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 839.8 1080" style="enable-background:new 0 0 839.8 1080;" xml:space="preserve">
  
  <path class="st0" d="M406.9,866.2C259.4,855.4,143,732.3,143,582.1c0-144,106.9-263.1,245.7-282.2"/>
  <path class="st0" d="M455.8,298.5c144.3,14,257.1,135.6,257.1,283.5c0,154.2-122.6,279.8-275.6,284.7"/>
  <path class="st0" d="M389.3,334.2c-0.8-42.1-1.2-70.2-1.3-75.5l0-0.9l0.8-0.3c3.1-1.1,6.2-4,9.3-8.7h-11c-3.5-0.3-14.6-0.2-19.8,5.4c-2,2.2-2.9,5-3,8.8l-0.1,14.6l-15.7-0.1l0.1-14.6c0-8.8,2.8-16.3,7.9-21.8c10.7-11.5,31.5-10.4,31.5-10.4h17.1c-1.2-11.7-3.7-39.8-3.6-74.5c0.1-30.4,5-61,6.7-70.8 M438.7,830.4c-4.1,73.2-9,127.9-14.7,141.9c-0.5,1.2-0.9,2-1.4,2.6l-1,1.2l-1-1.2c-6.2-7.8-11.5-65.2-15.8-144.3 M437.1,85.5c1.6,9.8,6.3,40.4,6.2,70.8c-0.1,34.7-2.8,62.7-4.1,74.4h18c0,0,14.9-0.2,19.8-5.4c2-2.2,2.9-5,3-8.8l0.1-14.6l15.7,0.1l-0.1,14.6c0,8.8-2.8,16.3-7.9,21.8c-10.7,11.5-28,10.7-31.5,10.5h-10.1c2.3,3.7,5.5,7.6,9.2,9l0.8,0.3l0,0.9c-0.1,5.3-0.5,33.2-1.4,75.2"/>
  <line class="st1" x1="431.9" y1="48.2" x2="447.1" y2="54.3"/>
  <line class="st1" x1="434.8" y1="60.5" x2="446.6" y2="65.3"/>
  <line class="st1" x1="433" y1="71" x2="443.9" y2="75.4"/>
  <line class="st1" x1="426.9" y1="79.7" x2="438.4" y2="84.4"/>
  <line class="st1" x1="421.8" y1="100" x2="442.2" y2="108.3"/>
  <line class="st1" x1="423" y1="111.6" x2="441.5" y2="119.2"/>
  <line class="st1" x1="420.2" y1="121.7" x2="443.1" y2="131"/>
  <line class="st1" x1="424.4" y1="134.6" x2="443.1" y2="142.2"/>
  <line class="st1" x1="425.6" y1="146.3" x2="442.9" y2="153.3"/>
  <line class="st1" x1="423.5" y1="156.6" x2="443.9" y2="164.9"/>
  <line class="st1" x1="424.1" y1="168" x2="443" y2="175.7"/>
  <line class="st1" x1="425.6" y1="179.8" x2="442.6" y2="186.7"/>
  <line class="st1" x1="425.6" y1="191" x2="442.2" y2="197.7"/>
  <line class="st1" x1="420.7" y1="200.2" x2="441.6" y2="208.7"/>
  <line class="st1" x1="423" y1="212.3" x2="439.8" y2="219.1"/>
  <line class="st1" x1="422.2" y1="223.2" x2="440" y2="230.4"/>
  <line class="st1" x1="438.8" y1="252.3" x2="456.1" y2="259.3"/>
  <line class="st1" x1="437.5" y1="262.9" x2="455.9" y2="270.4"/>
  <line class="st1" x1="436.6" y1="273.8" x2="455.8" y2="281.5"/>
  <line class="st1" x1="435.4" y1="284.5" x2="455.5" y2="292.6"/>
  <line class="st1" x1="434.3" y1="295.2" x2="456.1" y2="304"/>
  <line class="st1" x1="433.2" y1="305.9" x2="455.5" y2="315"/>
  <line class="st1" x1="432" y1="316.7" x2="454.9" y2="325.9"/>
  <line class="st1" x1="430.9" y1="327.4" x2="446.4" y2="333.7"/>
  <line class="st1" x1="420.8" y1="837.8" x2="437.9" y2="844.7"/>
  <line class="st1" x1="421.4" y1="849.2" x2="437.2" y2="855.6"/>
  <line class="st1" x1="421.7" y1="860.5" x2="436.3" y2="866.5"/>
  <line class="st1" x1="421.7" y1="871.7" x2="435.8" y2="877.4"/>
  <line class="st1" x1="421.4" y1="882.8" x2="435" y2="888.3"/>
  <line class="st1" x1="421.3" y1="893.9" x2="434.1" y2="899.1"/>
  <line class="st1" x1="421.6" y1="905.2" x2="433.2" y2="909.9"/>
  <line class="st1" x1="421" y1="916.2" x2="432.2" y2="920.7"/>
  <line class="st1" x1="421.4" y1="927.5" x2="431.1" y2="931.4"/>
  <line class="st1" x1="421.7" y1="938.8" x2="429.8" y2="942.1"/>
  <line class="st1" x1="413.4" y1="334.2" x2="405.1" y2="249.4"/>
  <line class="st1" x1="439.1" y1="249.6" x2="430.2" y2="334.2"/>
  <path class="st1" d="M421.6,830.6v143.5"/>
  <line class="st0" x1="398.1" y1="248.8" x2="445.7" y2="248.8"/>
  <line class="st0" x1="398.1" y1="230.7" x2="445.7" y2="230.7"/>
  <ellipse class="st0" cx="422.7" cy="60.9" rx="25.1" ry="28.7"/>
  <line class="st0" x1="480.3" y1="334.2" x2="370.5" y2="334.2"/>
  <line class="st0" x1="377.2" y1="830.6" x2="468.2" y2="830.6"/>
  <path class="st0" d="M340.1,707.8h59.7l24.3,25.7 M292.6,773.8l-26-24.3V390.9h49.7l24.3,25.7"/>
  <path class="st0" d="M462.1,774.5l-26.6-25V390.9h135.1l24.3,25.6 M509.1,707.8h61.6l24.3,25.9 M509.1,544.9h56.6l24.3,25.7"/>
  <path class="st0" d="M290.9,773.8V415.2h49.7v316.9H424v41.7H290.9z"/>
  <path class="st0" d="M459.8,773.8V415.2h135.1v41.7h-85.4v112.3h80.5v41.7h-80.5v121.2h85.4v41.7H459.8z"/>
  <line class="st0" x1="266.6" y1="390.9" x2="290.9" y2="415.2"/>
  <line class="st0" x1="435.5" y1="390.9" x2="459.8" y2="415.2"/>
  <path class="st0" d="M404.3,178.5h-367v447.6c0,98.6,16.3,170.2,69.6,231.3c61.3,70.4,202.3,139.4,275.1,166.8c24.2,9.1,39.4,22.1,39.4,22.1s15.2-13,39.4-22.1c72.8-27.4,213.7-96.5,275.1-166.8c53.3-61.1,69.6-132.7,69.6-231.3V178.5H443.7" />
  <line class="st0" x1="576" y1="314.2" x2="711.6" y2="178.5"/>
  <line class="st0" x1="76.1" y1="814.1" x2="161.6" y2="728.5"/>
  <line class="st0" x1="250" y1="829.6" x2="168.3" y2="911.4"/>
  <line class="st0" x1="804.6" y1="275" x2="676" y2="403.6"/>

</svg>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> animatedDelay fadeOutUp"><%= message %></div>
    <% end %>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <div class="message-user">
    <%= message.user.username %>:
  </div>
  <div class="message-content">
    <%= sanitize markdown_to_html(message.content) %>
  </div>
</div>

app/views/messages/_message_form.html.erb
<div class="message-input">
  <%= form_for(@message, remote: true) do |f| %>
    <%= f.text_area :content %>
    <%= f.submit "Send" %>
  <% end %>
</div>

app/views/messages/_messages.html.erb
<div id="messages" class="messages">
  <div id="messages-table" class="messages-table">
    <% if @messages.any? %>
      <%= render @messages %>
    <% end %>
  </div>
</div> 

app/views/messages/index.html.erb
<div class="message-wr">
  <%= render 'messages' %>
  <%= render 'message_form' %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="dialog">
  <h1>Sign up</h1>

  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Sign up" %>
  <% end %>
  <ul class="session-links">
    <li>Already have an account?</li>
    <li><%= link_to "Sign In", root_path %></li>
  </ul>
</div>